### ISSUE TITLE
i want enable linux desktop to this project.

### ISSUE THREAD

**Issue by bluesiboy** [MrNtlu/Asset-Manager-Flutter#1]
`
[Asset-Manager-Flutter] flutter create --platforms linux .
Loading '/home/blue/Codes/fdemos/Asset-Manager-Flutter/./ios/Runner/Info.plist' - non-NSData data argument passed to method
"Asset-Manager-Flutter" is not a valid Dart package name.

See https://dart.dev/tools/pub/pubspec#name for more information.
exit code 1
`

**Comment by MrNtlu** [comment]
I haven't enabled on Linux and also I don't have Linux to test. Currently only mobile is up-to-date and Mac's status is  okey-ish.

**Comment by MrNtlu** [comment]
Maybe you can check this. https://github.com/flutter/flutter/issues/53106
